---
# Docker server install

- name: "Install requirements"
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python-backports.ssl-match-hostname
    - python-docker
    state: present
    force_apt_get: yes
    update_cache: yes
    

- name: "Add Docker official GPG key:"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Add the official docker repo"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
    state: 'present'

- name: "Install the latest version of Docker CE"
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: present
    force_apt_get: yes
    update_cache: yes

- name: "Configuring remote access with systemd unit file"
  lineinfile:
    path: "/lib/systemd/system/docker.service"
    regexp: "^ExecStart=/usr/bin/dockerd"
    line: "ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock -H tcp://0.0.0.0:2375"

- name: Force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: 'Start the docker service'
  service:
    name: docker
    state: restarted
    enabled: yes