---
# Copy customozed html page to web-server dir

- debug: msg="{{ index_html_template[container_facts.ansible_facts.ansible_virtualization_type] }} , {{ nginx_root[ansible_distribution] }}"

# Copy customized html page
- name: "copy custom page"
  become: yes
  template:
    # src: index.html.j2
    src: "{{ index_html_template[container_facts.ansible_facts.ansible_virtualization_type] }}"
    dest: "{{ nginx_root[ansible_distribution] }}/index.html"
