---
- hosts: all
  tasks:
    - name: Install a list of packages.
      become: yes
      apt:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - ntp
        - bash-completion
        - tree
      notify:
      - restart ntp

  handlers:
    - name: restart ntp
      become: yes
      service: name=ntp state=restarted
